// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr0vYiC6lSfHLQQMIrgkezwl_RH8jUnS8',
    appId: '1:889159660113:android:b19b487ec5d8044e4dfe70',
    messagingSenderId: '889159660113',
    projectId: 'testing-82aaf',
    storageBucket: 'testing-82aaf.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyjryqH1qYn2FWTqdKKJ_jsgncA7R1lkw',
    appId: '1:889159660113:web:04a92958d176a88b4dfe70',
    messagingSenderId: '889159660113',
    projectId: 'testing-82aaf',
    authDomain: 'testing-82aaf.firebaseapp.com',
    storageBucket: 'testing-82aaf.firebasestorage.app',
    measurementId: 'G-1WEWW98P2Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9tyOkY5RtlbU9W949Boj1E_WervKr2TI',
    appId: '1:889159660113:ios:c07c6717bc5b60e24dfe70',
    messagingSenderId: '889159660113',
    projectId: 'testing-82aaf',
    storageBucket: 'testing-82aaf.firebasestorage.app',
    iosBundleId: 'com.example.owtest',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tyOkY5RtlbU9W949Boj1E_WervKr2TI',
    appId: '1:889159660113:ios:c07c6717bc5b60e24dfe70',
    messagingSenderId: '889159660113',
    projectId: 'testing-82aaf',
    storageBucket: 'testing-82aaf.firebasestorage.app',
    iosBundleId: 'com.example.owtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyjryqH1qYn2FWTqdKKJ_jsgncA7R1lkw',
    appId: '1:889159660113:web:04a92958d176a88b4dfe70',
    messagingSenderId: '889159660113',
    projectId: 'testing-82aaf',
    authDomain: 'testing-82aaf.firebaseapp.com',
    storageBucket: 'testing-82aaf.firebasestorage.app',
    measurementId: 'G-1WEWW98P2Y',
  );

}